# Generated by Django 2.2.6 on 2019-10-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questioon_text',
            new_name='question_text',
        ),
    ]
